"""initial migration

Revision ID: 5011715801b1
Revises: None
Create Date: 2014-12-31 00:52:57.353641

"""

# revision identifiers, used by Alembic.
revision = '5011715801b1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
